### ISSUE TITLE
SagePay Plugin intefers with PayPal and doesn't always work

### ISSUE THREAD

**Issue by schmoot** [andyplak/events-manager-pro-sage-pay#22] opened 2016-05-06 10:58 UTC
I have a serious problem. The SagePay plugin doesn't always work. I only works intermittently, some users get a blank screen instead of being returned to the website, this then fails to make the booking. In fact the booking isn't logged at all.

Also if I have the SagePay plugin activated it stops the PayPal gateway working, with similar results.

I have switched themes and turned off all other plugins, updated everything to the latest version, the only one that causes the problem is SagePay.

Please help!

**Comment by andyplak** [comment] 2016-05-06 14:35
Can you check your php error log on the server please? The blank screen implies a fatal error somewhere, so we can start by looking at that.

**Comment by schmoot** [comment] 2016-05-06 14:47
Hi Andy

Thanks for the quick response.

See attached, hopefully this is what you are looking for

Ruth

From:  Andy Place <notifications@github.com>
Reply-To:  andyplak/events-manager-pro-sage-pay
<reply+00a8c25c0b321536c57e4fc810be289ceb5f8b4bd5d702fb92cf0000000113446d999
2a169ce09252079@reply.github.com>
Date:  Friday, 6 May 2016 15:35
To:  andyplak/events-manager-pro-sage-pay
<events-manager-pro-sage-pay@noreply.github.com>
Cc:  Ruth Vant <ruth@dizzy-webdesign.co.uk>, Author
<author@noreply.github.com>
Subject:  Re: [andyplak/events-manager-pro-sage-pay] SagePay Plugin intefers
with PayPal and doesn't always work (#22)


Can you check your php error log on the server please? The blank screen
implies a fatal error somewhere, so we can start by looking at that.


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/andyplak/events-manager-pro-sage-pay/issues/22#issuecomm
ent-217457000>

**Comment by andyplak** [comment] 2016-05-09 10:57
@schmoot There are no errors in the PHP log that relate to the Sage Pay plugin or Events Manager. I'll need to try and see this happening to get a better understanding.

- At what stage does this blank screen appear? What is the url?
- For those payments, can you see the payment having gone through in the Sage Pay admin in
interface?
- Are you running SagePay in test or production mode?
- Does PayPal not work consistently when the SagePay gateway is enabled? What happens to a user who tries to pay via PayPal?

**Comment by schmoot** [comment] 2016-05-09 11:15
Hi Andy

The white screen appears when the transaction is complete on SagePay in live
mode (can¹t do test mode as they are using it on the live site for
WooCommerce).

This doesn¹t always happen. Sometimes it is completely successful, other
times it goes to white screen there doesn¹t appear to be any logic to when
this happens. Worse when you are registering a new user rather than being
logged in.

The payment is always successful, but the booking is not, depending on the
white screen.

Paypal payments go through and return to the site (no white screen), but no
booking is made on the site. I have got it to work intermittently, but only
works faultlessly with SagePay off.

Also if you cancel the booking you don¹t get the Complete booking¹ button
in My Bookings¹ if SagePay in enabled.

Here is the login to the dev site
http://pinkdev1.co.uk/wp-admin

info@andyplace.co.uk
&(4Z1@%F46!dolravu^$x!Q(

SagePay plugin is currently off, but you can activate for testing. The site
has been backed up.

There is a test event for 0.01p  http://pinkdev1.co.uk/events/may-testing/

As I mentioned before, I have tried with all other plugins off, all tweaks
to EM off and with a different theme and have the same issues.

Many thanks

Ruth



From:  Andy Place <notifications@github.com>
Reply-To:  andyplak/events-manager-pro-sage-pay
<reply+00a8c25c64b4d7af39bd94c3f9c96d64a67844e6331100e792cf0000000113482f379
2a169ce09252079@reply.github.com>
Date:  Monday, 9 May 2016 11:57
To:  andyplak/events-manager-pro-sage-pay
<events-manager-pro-sage-pay@noreply.github.com>
Cc:  Ruth Vant <ruth@dizzy-webdesign.co.uk>, Mention
<mention@noreply.github.com>
Subject:  Re: [andyplak/events-manager-pro-sage-pay] SagePay Plugin intefers
with PayPal and doesn't always work (#22)


@schmoot <https://github.com/schmoot>  There are no errors in the PHP log
that relate to the Sage Pay plugin or Events Manager. I'll need to try and
see this happening to get a better understanding.
* At what stage does this blank screen appear? What is the url?
* For those payments, can you see the payment having gone through in the
Sage Pay admin in interface?
* Are you running SagePay in test or production mode?
* Does PayPal not work consistently when the SagePay gateway is enabled?
What happens to a user who tries to pay via PayPal?

You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/andyplak/events-manager-pro-sage-pay/issues/22#issuecomm
ent-217835020>

**Comment by schmoot** [comment] 2016-05-12 14:36
Hello

Any news on this? 

Kind regards

Ruth

From:  Andy Place <notifications@github.com>
Reply-To:  andyplak/events-manager-pro-sage-pay
<reply+00a8c25c64b4d7af39bd94c3f9c96d64a67844e6331100e792cf0000000113482f379
2a169ce09252079@reply.github.com>
Date:  Monday, 9 May 2016 11:57
To:  andyplak/events-manager-pro-sage-pay
<events-manager-pro-sage-pay@noreply.github.com>
Cc:  Ruth Vant <ruth@dizzy-webdesign.co.uk>, Mention
<mention@noreply.github.com>
Subject:  Re: [andyplak/events-manager-pro-sage-pay] SagePay Plugin intefers
with PayPal and doesn't always work (#22)


@schmoot <https://github.com/schmoot>  There are no errors in the PHP log
that relate to the Sage Pay plugin or Events Manager. I'll need to try and
see this happening to get a better understanding.
* At what stage does this blank screen appear? What is the url?
* For those payments, can you see the payment having gone through in the
Sage Pay admin in interface?
* Are you running SagePay in test or production mode?
* Does PayPal not work consistently when the SagePay gateway is enabled?
What happens to a user who tries to pay via PayPal?

You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/andyplak/events-manager-pro-sage-pay/issues/22#issuecomm
ent-217835020>

**Comment by andyplak** [comment] 2016-05-13 08:19
Hi Ruth,

I've not had a spare moment to take a look at this yet I'm afraid. Contracted work has had to take priority. I'll take a look over the weekend if I don't find a slot today.

**Comment by andyplak** [comment] 2016-05-14 20:24
There is something very odd going on here, and it happens before even being redirected to SagePay. As a new user I go to create a booking, fill in all the details and then get redirected to SagePay, however there is no record of my booking in the Events Manager at all. Something is preventing this from being saved. I then go through and make the payment and when returning to Events Manager, the sage pay handler can't find a booking and then fails (ungracefully). Even more odd, this isn't happening 100% of the time. Sometimes the booking is saved.

I wonder if this lack of a booking being saved is also the cause of the odd behavior seen in #21.

@schmoot I see you've got some nice customisations on the booking form on the front end. Are these done via your theme? Do you hook in anywhere else as part of the booking process?

Can you test with all non Events Manager plugins disabled and with the Twenty Fourteen theme? I'm suspicious that something is interfering with the booking process (I've got multiple other people running this plugin without problems), so that will help confirm.

Is this a production site? Can we do live debugging?

**Comment by schmoot** [comment] 2016-05-15 08:44
Hello yes pinkdev1 is a development site for testing. Two files in em have been altered. But run just fine without sagepay and I did deactivated them before coming to you. In em pro the booking form .js file and in the main em plugin em-functions file we made some changes to the countries to make them match woocoomerce but that's it. You can deactivate all the other plugins to run a proper test

Hope that helps
Ruth

**Comment by andyplak** [comment] 2016-05-18 21:50
This is a bug with how the SagePay plugin deletes "Bookings Pending Payment". If any value is added to that setting, then the bookings are deleted. Queries in `em_gateway_sagepay_form_booking_timeout()` are selecting bookings that are within in the window.

**Comment by andyplak** [comment] 2016-05-18 22:18
@schmoot I've uploaded a version of the plugin with the above fix in it to your site. It's looking good, however can you test for me and confirm?

**Comment by andyplak** [comment] 2016-06-06 08:50
Fixed in [v1.5.8](https://github.com/andyplak/events-manager-pro-sage-pay/releases/tag/v1.5.8)

**Closed by andyplak** 2016-06-06 08:50 UTC
Labels: bug
