### ISSUE TITLE
Error: Bad Sage Pay request

### ISSUE THREAD

**Issue by schmoot** [andyplak/events-manager-pro-sage-pay#21] opened 2016-04-08 09:33 UTC
If you use the back buttons in the SagePay pop up it causes errors, i.e. if you go to a card, use the 'SagePay' back button (not browser) and then click the 'Cancel' button you get this error

Error: Bad Sage Pay request, custom ID does not correspond with any pending booking.

Also if you use back from the list of card and then choose another you get a link like this, but it doesn't do anything in Wordpress you just get a blank screen
http://www.kicc.org.uk/wp-admin/admin-ajax.php?action=em_payment&em_payment_gateway=sagepay_form&crypt=@d96d0bd549cb97ab4a39435b44aac38a4f07df2d44c289393f531568eef6d08be3999e1ea44e9096b2e9209aed5048b02a31061265a2565aa8d2dfc3ec4d25cf06eaa1ac736c723ae991bb0d2a39574fa55c746452f61ecc0b398d1aa16bc899f332981461bb2da9540ea21c311928612b5127f3c247b30a7d7ffe9496c441b657fa9d806f8e0f7aabadd429c98ded61536da7f4bb457accfb15979897849612dd187eb6264ae3bdd428ed0652a247e729390c98496b3ca9632d8dd49455fba50c4acdb0a5dffc36b444d4ed2964f5ea30c68596e994caa1b6a6288ed8914b512befb305b04e00a9a24be9931912a446e921e2f18bd899f2e959280ce7e63657ecb8caf92cc14206b29d8f61ea4b2fe1238a9d9ed7f6cf4e7935bf1f95f5ab5f10fcdee6963bbbdd1cb6cef605a78b367c34ea800ba8588618eb9100c82f932dce66ef837d0ea2662ba854ca591b1d0f1e3a465741e47af3e71de3291a3581a9d01227e99ccaaf9aba643b6a657811af

**Comment by andyplak** [comment] 2016-04-09 11:34
@schmoot thanks for reporting this. I've tried this, going to SagePay, then selecting the card, clicking back and then cancel. When I do so I get back to the Events Manager booking page and get this message:

_Payment Unsuccessful
You chose to Cancel your order on the Sage Pay payment pages._

I'm using a test account so that could be the reason. Do you have a link to an Event I can try it on?

Also, do you have anything configured under the "Return Fail URL" on the SagePay Gateway settings under Events Manager?
/wp-admin/edit.php?post_type=event&page=events-manager-gateways&action=edit&gateway=sagepay_form#general

**Comment by schmoot** [comment] 2016-04-09 11:44
Hello

Here is a live event
https://www.kicc.org.uk/events/igoc-the-international-gathering-of-champions
/

Here is the page that is set for cancelled bookings in the settings
http://www.kicc.org.uk/events-list/cancelled/

If you click cancel straight away it goes to that page, it¹s only when you
change your mind after selecting a card it doesn¹t work.

Many thanks

Ruth

From:  Andy Place <notifications@github.com>
Reply-To:  andyplak/events-manager-pro-sage-pay
<reply+00a8c25c279a25eb36e4df78ddcaf8171da1f582fe794fb492cf000000011320aacb9
2a169ce08c12500@reply.github.com>
Date:  Saturday, 9 April 2016 12:34
To:  andyplak/events-manager-pro-sage-pay
<events-manager-pro-sage-pay@noreply.github.com>
Cc:  Ruth Vant <ruth@dizzy-webdesign.co.uk>
Subject:  Re: [andyplak/events-manager-pro-sage-pay] Error: Bad Sage Pay
request (#21)


@schmoot <https://github.com/schmoot>  thanks for reporting this. I've tried
this, going to SagePay, then selecting the card, clicking back and then
cancel. When I do so I get back to the Events Manager booking page and get
this message:

Payment Unsuccessful
You chose to Cancel your order on the Sage Pay payment pages.

I'm using a test account so that could be the reason. Do you have a link to
an Event I can try it on?

Also, do you have anything configured under the "Return Fail URL" on the
SagePay Gateway settings under Events Manager?
/wp-admin/edit.php?post_type=event&page=events-manager-gateways&action=edit&
gateway=sagepay_form#general


You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/andyplak/events-manager-pro-sage-pay/issues/21#issuecomm
ent-207774596>

**Comment by andyplak** [comment] 2016-04-14 17:13
Thanks Ruth. I see it on your site now. The behavior is different there than when using a SagePay test account. For some reason SagePay is calling the payment notification url instead of the cancel url specified. This appears to be something going wrong at the SagePay end, however I'll check the docs to see if I can see anything related.

In the meantime, could you try removing the "Return Fail URL" and testing again to see if that makes any difference (I don't think it will, but I'd like to rule that out).

We can then approach Sage Pay directly to see if they can shed any light on it.

**Comment by schmoot** [comment] 2016-04-14 17:30
Hello

Ok thanks for looking. Can you let me know if it¹s SagePay please

Ruth

From:  Andy Place <notifications@github.com>
Reply-To:  andyplak/events-manager-pro-sage-pay
<reply+00a8c25cb83f5c9c3103889e23e6575ab120ca668e35265a92cf00000001132791d39
2a169ce08c12500@reply.github.com>
Date:  Thursday, 14 April 2016 18:13
To:  andyplak/events-manager-pro-sage-pay
<events-manager-pro-sage-pay@noreply.github.com>
Cc:  Ruth Vant <ruth@dizzy-webdesign.co.uk>
Subject:  Re: [andyplak/events-manager-pro-sage-pay] Error: Bad Sage Pay
request (#21)


Thanks Ruth. I see it on your site now. The behavior is different there than
when using a SagePay test account. For some reason SagePay is calling the
payment notification url instead of the cancel url specified. This appears
to be something going wrong at the SagePay end, however I'll check the docs
to see if I can see anything related.

In the meantime, could you try removing the "Return Fail URL" and testing
again to see if that makes any difference (I don't think it will, but I'd
like to rule that out).

We can then approach Sage Pay directly to see if they can shed any light on
it.


You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/andyplak/events-manager-pro-sage-pay/issues/21#issuecomm
ent-210055390>

**Comment by andyplak** [comment] 2016-04-14 21:06
I think the problem is with SagePay. I can see nothing in the docs to suggest it would handle the two different 'cancelling' scenarios differently.

I'll email them to quiz them on it, however could you test it without any value configured for the "Return Fail URL"? I just want to rule that out first.

**Comment by andyplak** [comment] 2016-05-14 20:05
This does appear to be related to the return fail url. If there is no value there, then it works as expected, regardless at which stage you cancel. When present we get a blank screen and "Error: Bad Sage Pay request, custom ID does not correspond with any pending booking" from cancel, and card selection -> cancel respectively. 

Clearly something is going wrong with the payment return handler when we have a url configured. I'll have a go at reproducing it locally now that I understand it better.

**Comment by andyplak** [comment] 2016-05-18 22:19
I think the payment return url is a red herring. This is almost certainly related to the issue described and fixed via #22 

@schmoot can you test this as well on your site and let me know if it is working as expected now?

**Comment by schmoot** [comment] 2016-05-19 09:24
Great

I will give it a test today and let you know.

Ruth

From:  Andy Place <notifications@github.com>
Reply-To:  andyplak/events-manager-pro-sage-pay
<reply+00a8c25c5f9e231c44fe8a2ac8ec478bf2bcfd32c8c9a03792cf000000011354ac829
2a169ce08c12500@reply.github.com>
Date:  Wednesday, 18 May 2016 23:19
To:  andyplak/events-manager-pro-sage-pay
<events-manager-pro-sage-pay@noreply.github.com>
Cc:  Ruth Vant <ruth@dizzy-webdesign.co.uk>, Mention
<mention@noreply.github.com>
Subject:  Re: [andyplak/events-manager-pro-sage-pay] Error: Bad Sage Pay
request (#21)


I think the payment return url is a red herring. This is almost certainly
related to the issue described and fixed via #22
<https://github.com/andyplak/events-manager-pro-sage-pay/issues/22>

@schmoot <https://github.com/schmoot>  can you test this as well on your
site and let me know if it is working as expected now?


You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/andyplak/events-manager-pro-sage-pay/issues/21#issuecomm
ent-220175452>

**Comment by schmoot** [comment] 2016-05-19 10:30
Hi Andy

All tests looking good.

Thanks for all your help

Kind regards

Ruth

From:  Andy Place <notifications@github.com>
Reply-To:  andyplak/events-manager-pro-sage-pay
<reply+00a8c25c5f9e231c44fe8a2ac8ec478bf2bcfd32c8c9a03792cf000000011354ac829
2a169ce08c12500@reply.github.com>
Date:  Wednesday, 18 May 2016 23:19
To:  andyplak/events-manager-pro-sage-pay
<events-manager-pro-sage-pay@noreply.github.com>
Cc:  Ruth Vant <ruth@dizzy-webdesign.co.uk>, Mention
<mention@noreply.github.com>
Subject:  Re: [andyplak/events-manager-pro-sage-pay] Error: Bad Sage Pay
request (#21)


I think the payment return url is a red herring. This is almost certainly
related to the issue described and fixed via #22
<https://github.com/andyplak/events-manager-pro-sage-pay/issues/22>

@schmoot <https://github.com/schmoot>  can you test this as well on your
site and let me know if it is working as expected now?


You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/andyplak/events-manager-pro-sage-pay/issues/21#issuecomm
ent-220175452>

**Comment by andyplak** [comment] 2016-06-06 08:49
Fixed in [v1.5.8](https://github.com/andyplak/events-manager-pro-sage-pay/releases/tag/v1.5.8)

**Closed by andyplak** 2016-06-06 08:49 UTC
Labels: bug
